### ISSUE TITLE
Creación de la vista Checkout

### ISSUE THREAD

**Issue by LiliaSaid** [RominaRojas/ProyectoFinal-Muebleria#14]
@lauralozan0  Se mostrará por pantalla tres columnas la primera contendrá el producto a comprar, la segunda resumen de la compra en cual se mostrará el total a pagar y la tercera nos pedirá los datos de la tarjeta de credito(Num de tarjeta, vencimiento(mes , año), codigo de seguridad(3num)).

**Comment by lauralozan0** [comment]
tarea finalizada
