### ISSUE TITLE
Creación clase Product

### ISSUE THREAD

**Issue by LiliaSaid** [RominaRojas/ProyectoFinal-Muebleria#6]
@CRISTIANCELINCRUZ con sus metodos accesores y constructor parametrizado

**Comment by CRISTIANCELINCRUZ** [comment]
TAREA FINALIZADA
CREACIÓN DE LA CLASE Product CON SU CONSTRUCTOR POR DEFECTO, CONSTRUCTOR PARAMETRIZADO Y Getter and Seter DENTRO DEL PAQUETE aplicacion.modelo.dominio
